language: python

python:

  - "2.7"

  - "3.3"

  - "3.4"

  - "3.5"

  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa

  # maintainers to fix their pypy-dev package.

  - "pypy"

# command to install dependencies

install:

  - pip install .

  - pip install -r requirements.txt

  - python setup.py -q install

# command to run tests

script: python setup.py test
